nome = input("Qual seu nome?")
print('Seja bem vindo', nome)
PV = float(input('Digite o primeiro valor: '))
PS = float(input('Digite o primeiro valor: '))
tempo = float(input('Digite o tempo: '))
resultado = (PV + (PS * tempo))
print('A posição dele é ' ,  resultado)
pergunta = input('Deseja continuar?')
if (pergunta == 'sim'):
        PV = float(input('Digite o primeiro valor: '))
        PS = float(input('Digite o primeiro valor: '))
        tempo = float(input('Digite o tempo: '))
        resultado = (PV + (PS * tempo))
        print('A posição dele é ', resultado)
        pergunta = 'nao'
